# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_xtc', [dirname(__file__)])
        except ImportError:
            import _xtc
            return _xtc
        if fp is not None:
            try:
                _mod = imp.load_module('_xtc', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _xtc = swig_import_helper()
    del swig_import_helper
else:
    import _xtc
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class StopIteration(Exception):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StopIteration, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StopIteration, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xtc.new_StopIteration()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _xtc.delete_StopIteration
    __del__ = lambda self : None;
StopIteration_swigregister = _xtc.StopIteration_swigregister
StopIteration_swigregister(StopIteration)

class TypeError(Exception):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TypeError, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TypeError, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _xtc.new_TypeError()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _xtc.delete_TypeError
    __del__ = lambda self : None;
TypeError_swigregister = _xtc.TypeError_swigregister
TypeError_swigregister(TypeError)

class XTCReader(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, XTCReader, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, XTCReader, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _xtc.new_XTCReader(*args)
        try: self.this.append(this)
        except: self.this = this
    def set_outarray(self, *args): return _xtc.XTCReader_set_outarray(self, *args)
    def next(self): return _xtc.XTCReader_next(self)
    def __iter__(self): return _xtc.XTCReader___iter__(self)
    __swig_destroy__ = _xtc.delete_XTCReader
    __del__ = lambda self : None;
XTCReader_swigregister = _xtc.XTCReader_swigregister
XTCReader_swigregister(XTCReader)



