package:
  name: mdtraj
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../../

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python
    - cython
    - numpy x.x
    - setuptools
    - zlib

  run:
    - python
    - setuptools
    - numpy x.x
    - pandas
    - scipy
    - pytables

test:
  requires:
    - nose
    - scripttest
    - networkx
    - matplotlib
    - pandas
    - openmm  # [not (win32 or (win and py2k))]
    - shiftx2 # [linux]
    - nbformat
    - ipykernel
    - scikit-learn

  source_files:
    - examples/*

  commands:
    - nosetests mdtraj -v -s
    - cd examples && nosetests test_examples.py -v -s # [not (win32 or (win and py2k))]

about:
  home: http://mdtraj.org
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A modern, open library for the analysis of molecular dynamics trajectories (development snapshot)
