package:
  name: mdtraj-dev
  version: !!str 1.4.0.dev0

build:
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python
    - cython
    - numpy
    - setuptools

  run:
    - python
    - setuptools
    - argparse # [py26]
    - ordereddict # [py26]
    - numpy
    - pandas
    - scipy
    - pytables

test:
  requires:
    - nose
    - scripttest
    - networkx
    # Hack to install shiftx2 on travis
    {{ '- shiftx2' if environ.get('TRAVIS', False) == 'true' }}

    # Hack for py26. Get pip for extra dependencies that arent in
    # conda packages.
    - pip # [py26]
  commands:
    # HACK for py26. We need the importlib backport, but it's not in
    # the main conda repos and I don't feel like adding it to omnia.
    - pip install importlib # [py26]
    - nosetests mdtraj -v

about:
  home: http://mdtraj.org
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A modern, open library for the analysis of molecular dynamics trajectories (development snapshot)
