package:
  name: mdtraj
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../../

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - zlib 1.2.8
    - msinttypes  # [win and py27]

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - pandas
    - pytables

test:
  requires:
    - pytest
    - networkx
    - matplotlib
    - openmm  # [not (win32 or (win and py2k))]
    - shiftx2  # [linux and py2k]
    - nbformat
    - ipykernel
    - scikit-learn

  source_files:
    - examples/*
    - pytest.ini
    - tests/*

  imports:
    - mdtraj

  commands:
    - pytest tests/test_nmr.py

about:
  home: https://github.com/mdtraj/mdtraj
  license: LGPL-2.1
  summary: "A modern, open library for the analysis of molecular dynamics trajectories"
  description: |
    MDTraj is a python library that allows users to manipulate molecular dynamics
    (MD) trajectories and perform a variety of analyses, including fast RMSD,
    solvent accessible surface area, hydrogen bonding, etc. A highlight of MDTraj
    is the wide variety of molecular dynamics trajectory file formats which are
    supported, including RCSB pdb, GROMACS xtc, tng, and trr, CHARMM / NAMD dcd, AMBER
    binpos, AMBER NetCDF, AMBER mdcrd, TINKER arc and MDTraj HDF5.
  doc_url: http://mdtraj.org/
  dev_url: https://github.com/mdtraj/mdtraj
