package:
  name: mdtraj
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../../

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point
  script_env:
   - MDTRAJ_TEST_PEP517

requirements:
  build:
    - python
    - setuptools
    - cython  # [not os.getenv('MDTRAJ_TEST_PEP517', False)]
    - numpy  # [not os.getenv('MDTRAJ_TEST_PEP517', False)]
    - zlib
    - msinttypes  # [win and py27]
    - pip

  run:
    - python
    - setuptools
    - numpy
    - scipy
    # Fix pytables on windows. See https://github.com/conda-forge/pytables-feedstock/issues/31#issuecomment-410695814
    - snappy  # [win]

test:
  requires:
    - pytest
    - networkx
    - matplotlib
    - openmm >=7.1  # [not (win32 or (win and py2k) or py37)]
    - shiftx2  # [linux and py2k]
    # do not install cpptraj on osx, because the current version from omnia is linked against an old runtime.
    # and not avail on win
    - cpptraj  # [not (osx or win32 or win64)]
    - nbformat
    - ipykernel
    - scikit-learn
    - pytest-ignore-flaky
    - pandas
    - pytables

  source_files:
    - examples/*
    - pytest.ini
    - tests/*

  imports:
    - mdtraj

  commands:
    - pytest -v --ignore-flaky

about:
  home: https://github.com/mdtraj/mdtraj
  license: LGPL-2.1
  summary: "A modern, open library for the analysis of molecular dynamics trajectories"
  description: |
    MDTraj is a python library that allows users to manipulate molecular dynamics
    (MD) trajectories and perform a variety of analyses, including fast RMSD,
    solvent accessible surface area, hydrogen bonding, etc. A highlight of MDTraj
    is the wide variety of molecular dynamics trajectory file formats which are
    supported, including RCSB pdb, GROMACS xtc, tng, and trr, CHARMM / NAMD dcd, AMBER
    binpos, AMBER NetCDF, AMBER mdcrd, TINKER arc and MDTraj HDF5.
  doc_url: http://mdtraj.org/
  dev_url: https://github.com/mdtraj/mdtraj
