package:
  name: mdtraj-dev
  version: "0.0.0"

build:
  entry_points:
    - mdconvert = mdtraj.scripts.mdconvert:entry_point
    - mdinspect = mdtraj.scripts.mdinspect:entry_point

requirements:
  build:
    - python
    - cython
    - numpy x.x
    - setuptools

  run:
    - python
    - setuptools
    - numpy x.x
    - pandas
    - scipy
    - pytables

test:
  requires:
    - nose
    - scripttest
    - networkx
    - ipython-notebook
    - ipywidgets
    - matplotlib
    - pandas
    - openmm  # [not win32]
    - shiftx2 # [not win]

  commands:
    - nosetests mdtraj -v -s

about:
  home: http://mdtraj.org
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A modern, open library for the analysis of molecular dynamics trajectories (development snapshot)
