##############################################################################
# MDTraj: A Python Library for Loading, Saving, and Manipulating
#         Molecular Dynamics Trajectories.
# Copyright 2012-2014 Stanford University and the Authors
#
# Authors: Carlos X. Hernandez
# Contributors: Robert McGibbon, Jason Swails
#
# MDTraj is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 2.1
# of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with MDTraj. If not, see <http://www.gnu.org/licenses/>.
##############################################################################

_SOLVENT_TYPES = frozenset(
    [
        "118",
        "119",
        "1AL",
        "1CU",
        "2FK",
        "2HP",
        "2OF",
        "3CO",
        "3MT",
        "3NI",
        "3OF",
        "4MO",
        "543",
        "6MO",
        "ACT",
        "AG",
        "AL",
        "ALF",
        "ATH",
        "AU",
        "AU3",
        "AUC",
        "AZI",
        "Ag",
        "BA",
        "BAR",
        "BCT",
        "BEF",
        "BF4",
        "BO4",
        "BR",
        "BS3",
        "BSY",
        "Be",
        "CA",
        "CA+2",
        "Ca+2",
        "CAC",
        "CAD",
        "CAL",
        "CD",
        "CD1",
        "CD3",
        "CD5",
        "CE",
        "CES",
        "CHT",
        "CL",
        "CL-",
        "CLA",
        "Cl-",
        "CO",
        "CO3",
        "CO5",
        "CON",
        "CR",
        "CS",
        "CSB",
        "CU",
        "CU1",
        "CU3",
        "CUA",
        "CUZ",
        "CYN",
        "Cl-",
        "Cr",
        "DME",
        "DMI",
        "DSC",
        "DTI",
        "DY",
        "E4N",
        "EDR",
        "EMC",
        "ER3",
        "EU",
        "EU3",
        "F",
        "FE",
        "FE2",
        "FPO",
        "GA",
        "GD3",
        "GEP",
        "HAI",
        "HG",
        "HGC",
        "HOH",
        "IN",
        "IOD",
        "ION",
        "IR",
        "IR3",
        "IRI",
        "IUM",
        "K",
        "K+",
        "KO4",
        "LA",
        "LCO",
        "LCP",
        "LI",
        "LIT",
        "LU",
        "MAC",
        "MG",
        "MH2",
        "MH3",
        "MLI",
        "MMC",
        "MN",
        "MN3",
        "MN5",
        "MN6",
        "MO1",
        "MO2",
        "MO3",
        "MO4",
        "MO5",
        "MO6",
        "MOO",
        "MOS",
        "MOW",
        "MW1",
        "MW2",
        "MW3",
        "NA",
        "NA+2",
        "NA2",
        "NA5",
        "NA6",
        "NAO",
        "NAW",
        "Na+2",
        "NET",
        "NH4",
        "NI",
        "NI1",
        "NI2",
        "NI3",
        "NO2",
        "NO3",
        "NRU",
        "Na+",
        "O4M",
        "OAA",
        "OC1",
        "OC2",
        "OC3",
        "OC4",
        "OC5",
        "OC6",
        "OC7",
        "OC8",
        "OCL",
        "OCM",
        "OCN",
        "OCO",
        "OF1",
        "OF2",
        "OF3",
        "OH",
        "OS",
        "OS4",
        "OXL",
        "PB",
        "PBM",
        "PD",
        "PER",
        "PI",
        "PO3",
        "PO4",
        "POT",
        "PR",
        "PT",
        "PT4",
        "PTN",
        "RB",
        "RH3",
        "RHD",
        "RU",
        "RUB",
        "Ra",
        "SB",
        "SCN",
        "SE4",
        "SEK",
        "SM",
        "SMO",
        "SO3",
        "SO4",
        "SOD",
        "SR",
        "Sm",
        "Sn",
        "T1A",
        "TB",
        "TBA",
        "TCN",
        "TEA",
        "THE",
        "TL",
        "TMA",
        "TRA",
        "UNX",
        "V",
        "V2+",
        "VN3",
        "VO4",
        "W",
        "WO5",
        "Y1",
        "YB",
        "YB2",
        "YH",
        "YT3",
        "ZN",
        "ZN2",
        "ZN3",
        "ZNA",
        "ZNO",
        "ZO3",
    ],
)


_WATER_RESIDUES = frozenset(
    [
        "H2O",
        "HHO",
        "OHH",
        "HOH",
        "OH2",
        "SOL",
        "WAT",
        "TIP",
        "TIP2",
        "TIP3",
        "TIP4",
    ],
)


_AMINO_ACID_CODES = {
    "ACE": None,
    "NME": None,
    "00C": "X",
    "01W": "X",
    "02K": "X",
    "02L": "X",
    "03Y": "X",
    "07O": "X",
    "08P": "X",
    "0A0": "X",
    "0A1": "X",
    "0A2": "X",
    "0A8": "X",
    "0AA": "X",
    "0AB": "X",
    "0AC": "X",
    "0AF": "X",
    "0AG": "X",
    "0AH": "X",
    "0AK": "X",
    "0BN": "X",
    "0CS": "X",
    "0E5": "X",
    "0EA": "X",
    "0FL": "X",
    "0NC": "X",
    "0WZ": "X",
    "0Y8": "X",
    "143": "X",
    "193": "X",
    "1OP": "X",
    "1PA": "X",
    "1PI": "X",
    "1TQ": "X",
    "1TY": "X",
    "1X6": "X",
    "200": "X",
    "23F": "X",
    "23S": "X",
    "26B": "X",
    "2AD": "X",
    "2AG": "X",
    "2AO": "X",
    "2AS": "X",
    "2CO": "X",
    "2DO": "X",
    "2FM": "X",
    "2HF": "X",
    "2KK": "X",
    "2KP": "X",
    "2LU": "X",
    "2ML": "X",
    "2MR": "X",
    "2MT": "X",
    "2OR": "X",
    "2PI": "X",
    "2QZ": "X",
    "2R3": "X",
    "2SI": "X",
    "2TL": "X",
    "2TY": "X",
    "2VA": "X",
    "2XA": "X",
    "32S": "X",
    "32T": "X",
    "33X": "X",
    "3AH": "X",
    "3AR": "X",
    "3CF": "X",
    "3GA": "X",
    "3MD": "X",
    "3NF": "X",
    "3QN": "X",
    "3TY": "X",
    "3XH": "X",
    "4BF": "X",
    "4CF": "X",
    "4CY": "X",
    "4DP": "X",
    "4FB": "X",
    "4FW": "X",
    "4HT": "X",
    "4IN": "X",
    "4MM": "X",
    "4PH": "X",
    "4U7": "X",
    "56A": "X",
    "5AB": "X",
    "5CS": "X",
    "5CW": "X",
    "5HP": "X",
    "6CL": "X",
    "6CW": "X",
    "6GL": "X",
    "6HN": "X",
    "7JA": "X",
    "9NE": "X",
    "9NF": "X",
    "9NR": "X",
    "9NV": "X",
    "A5N": "X",
    "A66": "X",
    "AA3": "X",
    "AA4": "X",
    "AAR": "X",
    "AB7": "X",
    "ABA": "X",
    "ACB": "X",
    "ACL": "X",
    "ADD": "X",
    "AEA": "X",
    "AEI": "X",
    "AFA": "X",
    "AGM": "X",
    "AGT": "X",
    "AHB": "X",
    "AHH": "X",
    "AHO": "X",
    "AHP": "X",
    "AHS": "X",
    "AHT": "X",
    "AIB": "X",
    "AKL": "X",
    "AKZ": "X",
    "ALA": "A",
    "ALC": "X",
    "ALM": "X",
    "ALN": "X",
    "ALO": "X",
    "ALS": "X",
    "ALT": "X",
    "ALV": "X",
    "ALY": "X",
    "AN8": "X",
    "APE": "X",
    "APH": "X",
    "API": "X",
    "APK": "X",
    "APM": "X",
    "APP": "X",
    "AR2": "X",
    "AR4": "X",
    "AR7": "X",
    "ARG": "R",
    "ARM": "X",
    "ARO": "X",
    "ARV": "X",
    "AS2": "X",
    "AS9": "X",
    "ASA": "X",
    "ASB": "X",
    "ASI": "X",
    "ASK": "X",
    "ASL": "X",
    "ASM": "X",
    "ASN": "N",
    "ASP": "D",
    "ASQ": "X",
    "ASX": "X",
    "AVN": "X",
    "AYA": "X",
    "AZK": "X",
    "AZS": "X",
    "AZY": "X",
    "B1F": "X",
    "B2A": "X",
    "B2F": "X",
    "B2I": "X",
    "B2V": "X",
    "B3A": "X",
    "B3D": "X",
    "B3E": "X",
    "B3K": "X",
    "B3L": "X",
    "B3M": "X",
    "B3Q": "X",
    "B3S": "X",
    "B3T": "X",
    "B3U": "X",
    "B3X": "X",
    "B3Y": "X",
    "BB6": "X",
    "BB7": "X",
    "BB8": "X",
    "BB9": "X",
    "BBC": "X",
    "BCS": "X",
    "BE2": "X",
    "BFD": "X",
    "BG1": "X",
    "BH2": "X",
    "BHD": "X",
    "BIF": "X",
    "BIL": "X",
    "BIU": "X",
    "BJH": "X",
    "BL2": "X",
    "BLE": "X",
    "BLY": "X",
    "BMT": "X",
    "BNN": "X",
    "BNO": "X",
    "BOR": "X",
    "BPE": "X",
    "BSE": "X",
    "BTA": "X",
    "BTC": "X",
    "BTR": "X",
    "BUC": "X",
    "BUG": "X",
    "C1X": "X",
    "C22": "X",
    "C3Y": "X",
    "C4R": "X",
    "C5C": "X",
    "C66": "X",
    "C6C": "X",
    "CAF": "X",
    "CAL": "X",
    "CAS": "X",
    "CAV": "X",
    "CAY": "X",
    "CCL": "X",
    "CCS": "X",
    "CDE": "X",
    "CDV": "X",
    "CEA": "X",
    "CGA": "X",
    "CGU": "X",
    "CHF": "X",
    "CHG": "X",
    "CHP": "X",
    "CHS": "X",
    "CIR": "X",
    "CLE": "X",
    "CLG": "X",
    "CLH": "X",
    "CME": "X",
    "CMH": "X",
    "CML": "X",
    "CMT": "X",
    "CPC": "X",
    "CPI": "X",
    "CR5": "X",
    "CS0": "X",
    "CS1": "X",
    "CS3": "X",
    "CS4": "X",
    "CSA": "X",
    "CSB": "X",
    "CSD": "X",
    "CSE": "X",
    "CSJ": "X",
    "CSO": "X",
    "CSP": "X",
    "CSR": "X",
    "CSS": "X",
    "CSU": "X",
    "CSW": "X",
    "CSX": "X",
    "CSZ": "X",
    "CTE": "X",
    "CTH": "X",
    "CUC": "X",
    "CWR": "X",
    "CXM": "X",
    "CY0": "X",
    "CY1": "X",
    "CY3": "X",
    "CY4": "X",
    "CYA": "X",
    "CYD": "X",
    "CYF": "X",
    "CYG": "X",
    "CYJ": "X",
    "CYM": "X",
    "CYQ": "X",
    "CYR": "X",
    "CYS": "C",
    "CZ2": "X",
    "CZZ": "X",
    "D11": "X",
    "D3P": "X",
    "D4P": "X",
    "DA2": "X",
    "DAB": "X",
    "DAH": "X",
    "DAL": "X",
    "DAR": "X",
    "DAS": "X",
    "DBB": "X",
    "DBS": "X",
    "DBU": "X",
    "DBY": "X",
    "DBZ": "X",
    "DC2": "X",
    "DCL": "X",
    "DCY": "X",
    "DDE": "X",
    "DFI": "X",
    "DFO": "X",
    "DGH": "X",
    "DGL": "X",
    "DGN": "X",
    "DHA": "X",
    "DHI": "X",
    "DHL": "X",
    "DHN": "X",
    "DHP": "X",
    "DHV": "X",
    "DI7": "X",
    "DIL": "X",
    "DIR": "X",
    "DIV": "X",
    "DLE": "X",
    "DLS": "X",
    "DLY": "X",
    "DM0": "X",
    "DMH": "X",
    "DMK": "X",
    "DMT": "X",
    "DNE": "X",
    "DNL": "X",
    "DNP": "X",
    "DNS": "X",
    "DOA": "X",
    "DOH": "X",
    "DON": "X",
    "DPL": "X",
    "DPN": "X",
    "DPP": "X",
    "DPQ": "X",
    "DPR": "X",
    "DSE": "X",
    "DSG": "X",
    "DSN": "X",
    "DSP": "X",
    "DTH": "X",
    "DTR": "X",
    "DTY": "X",
    "DVA": "X",
    "DYS": "X",
    "ECC": "X",
    "EFC": "X",
    "EHP": "X",
    "ESB": "X",
    "ESC": "X",
    "EXY": "X",
    "EYS": "X",
    "F2F": "X",
    "FAK": "X",
    "FB5": "X",
    "FB6": "X",
    "FCL": "X",
    "FGA": "X",
    "FGL": "X",
    "FGP": "X",
    "FH7": "X",
    "FHL": "X",
    "FHO": "X",
    "FLA": "X",
    "FLE": "X",
    "FLT": "X",
    "FME": "X",
    "FOE": "X",
    "FP9": "X",
    "FRD": "X",
    "FT6": "X",
    "FTR": "X",
    "FTY": "X",
    "FVA": "X",
    "FZN": "X",
    "GAU": "X",
    "GCM": "X",
    "GFT": "X",
    "GGL": "X",
    "GHG": "X",
    "GHP": "X",
    "GL3": "X",
    "GLH": "X",
    "GLJ": "X",
    "GLK": "X",
    "GLM": "X",
    "GLN": "Q",
    "GLQ": "X",
    "GLU": "E",
    "GLX": "X",
    "GLY": "G",
    "GLZ": "X",
    "GMA": "X",
    "GND": "X",
    "GPL": "X",
    "GSC": "X",
    "GSU": "X",
    "GT9": "X",
    "GVL": "X",
    "H14": "X",
    "H5M": "X",
    "HAC": "X",
    "HAR": "X",
    "HBN": "X",
    "HCS": "X",
    "HFA": "X",
    "HGL": "X",
    "HHI": "X",
    "HIA": "X",
    "HIC": "X",
    "HIP": "X",
    "HIQ": "X",
    "HIS": "H",
    "HL2": "X",
    "HLU": "X",
    "HMR": "X",
    "HPC": "X",
    "HPE": "X",
    "HPH": "X",
    "HPQ": "X",
    "HQA": "X",
    "HRG": "X",
    "HRP": "X",
    "HS8": "X",
    "HS9": "X",
    "HSE": "X",
    "HSD": "X",
    "HSL": "X",
    "HSO": "X",
    "HTI": "X",
    "HTN": "X",
    "HTR": "X",
    "HV5": "X",
    "HVA": "X",
    "HY3": "X",
    "HYP": "X",
    "HZP": "X",
    "I2M": "X",
    "I58": "X",
    "IAM": "X",
    "IAR": "X",
    "IAS": "X",
    "IEL": "X",
    "IGL": "X",
    "IIL": "X",
    "ILE": "I",
    "ILG": "X",
    "ILX": "X",
    "IML": "X",
    "IOY": "X",
    "IPG": "X",
    "IT1": "X",
    "IYR": "X",
    "IYT": "X",
    "IZO": "X",
    "JJJ": "X",
    "JJK": "X",
    "JJL": "X",
    "K1R": "X",
    "KCX": "X",
    "KGC": "X",
    "KNB": "X",
    "KOR": "X",
    "KPI": "X",
    "KST": "X",
    "KYN": "X",
    "KYQ": "X",
    "L2A": "X",
    "LA2": "X",
    "LAA": "X",
    "LAL": "X",
    "LBY": "X",
    "LCK": "X",
    "LCX": "X",
    "LCZ": "X",
    "LDH": "X",
    "LED": "X",
    "LEF": "X",
    "LEH": "X",
    "LEI": "X",
    "LEM": "X",
    "LEN": "X",
    "LET": "X",
    "LEU": "L",
    "LEX": "X",
    "LHC": "X",
    "LLP": "X",
    "LLY": "X",
    "LME": "X",
    "LMF": "X",
    "LMQ": "X",
    "LP6": "X",
    "LPD": "X",
    "LPG": "X",
    "LPL": "X",
    "LPS": "X",
    "LSO": "X",
    "LTA": "X",
    "LTR": "X",
    "LVG": "X",
    "LVN": "X",
    "LYF": "X",
    "LYK": "X",
    "LYM": "X",
    "LYN": "X",
    "LYR": "X",
    "LYS": "K",
    "LYX": "X",
    "LYZ": "X",
    "M0H": "X",
    "M2L": "X",
    "M2S": "X",
    "M30": "X",
    "M3L": "X",
    "MA ": "X",
    "MAA": "X",
    "MAI": "X",
    "MBQ": "X",
    "MC1": "X",
    "MCG": "X",
    "MCL": "X",
    "MCS": "X",
    "MD3": "X",
    "MD6": "X",
    "MDF": "X",
    "MDH": "X",
    "MEA": "X",
    "MED": "X",
    "MEG": "X",
    "MEN": "X",
    "MEQ": "X",
    "MET": "M",
    "MEU": "X",
    "MF3": "X",
    "MGG": "X",
    "MGN": "X",
    "MGY": "X",
    "MHL": "X",
    "MHO": "X",
    "MHS": "X",
    "MIS": "X",
    "MK8": "X",
    "ML3": "X",
    "MLE": "X",
    "MLL": "X",
    "MLY": "X",
    "MLZ": "X",
    "MME": "X",
    "MMO": "X",
    "MND": "X",
    "MNL": "X",
    "MNV": "X",
    "MOD": "X",
    "MP8": "X",
    "MPH": "X",
    "MPJ": "X",
    "MPQ": "X",
    "MSA": "X",
    "MSE": "X",
    "MSL": "X",
    "MSO": "X",
    "MSP": "X",
    "MT2": "X",
    "MTY": "X",
    "MVA": "X",
    "N10": "X",
    "N2C": "X",
    "N7P": "X",
    "N80": "X",
    "N8P": "X",
    "NA8": "X",
    "NAL": "X",
    "NAM": "X",
    "NB8": "X",
    "NBQ": "X",
    "NC1": "X",
    "NCB": "X",
    "NCY": "X",
    "NDF": "X",
    "NEM": "X",
    "NEP": "X",
    "NFA": "X",
    "NHL": "X",
    "NIY": "X",
    "NLE": "X",
    "NLN": "X",
    "NLO": "X",
    "NLP": "X",
    "NLQ": "X",
    "NMC": "X",
    "NMM": "X",
    "NNH": "X",
    "NPH": "X",
    "NPI": "X",
    "NSK": "X",
    "NTR": "X",
    "NTY": "X",
    "NVA": "X",
    "NYS": "X",
    "NZH": "X",
    "O12": "X",
    "OAR": "X",
    "OAS": "X",
    "OBF": "X",
    "OBS": "X",
    "OCS": "X",
    "OCY": "X",
    "OHI": "X",
    "OHS": "X",
    "OIC": "X",
    "OLE": "X",
    "OLT": "X",
    "OLZ": "X",
    "OMT": "X",
    "ONH": "X",
    "ONL": "X",
    "OPR": "X",
    "ORN": "X",
    "ORQ": "X",
    "OSE": "X",
    "OTB": "X",
    "OTH": "X",
    "OXX": "X",
    "P1L": "X",
    "P2Y": "X",
    "PAQ": "X",
    "PAS": "X",
    "PAT": "X",
    "PAU": "X",
    "PBB": "X",
    "PBF": "X",
    "PCA": "X",
    "PCC": "X",
    "PCE": "X",
    "PCS": "X",
    "PDL": "X",
    "PEC": "X",
    "PF5": "X",
    "PFF": "X",
    "PFX": "X",
    "PG1": "X",
    "PG9": "X",
    "PGL": "X",
    "PGY": "X",
    "PH6": "X",
    "PHA": "X",
    "PHD": "X",
    "PHE": "F",
    "PHI": "X",
    "PHL": "X",
    "PHM": "X",
    "PIV": "X",
    "PLE": "X",
    "PM3": "X",
    "POM": "X",
    "PPN": "X",
    "PR3": "X",
    "PR9": "X",
    "PRO": "P",
    "PRS": "X",
    "PSA": "X",
    "PSH": "X",
    "PTA": "X",
    "PTH": "X",
    "PTM": "X",
    "PTR": "X",
    "PVH": "X",
    "PVL": "X",
    "PYA": "X",
    "PYL": "X",
    "PYX": "X",
    "QCS": "X",
    "QMM": "X",
    "QPA": "X",
    "QPH": "X",
    "R1A": "X",
    "R4K": "X",
    "RE0": "X",
    "RE3": "X",
    "RON": "X",
    "RVX": "X",
    "RZ4": "X",
    "S1H": "X",
    "S2C": "X",
    "S2D": "X",
    "S2P": "X",
    "SAC": "X",
    "SAH": "X",
    "SAR": "X",
    "SBL": "X",
    "SCH": "X",
    "SCS": "X",
    "SCY": "X",
    "SD2": "X",
    "SDP": "X",
    "SE7": "X",
    "SEB": "X",
    "SEC": "X",
    "SEG": "X",
    "SEL": "X",
    "SEM": "X",
    "SEN": "X",
    "SEP": "X",
    "SER": "S",
    "SET": "X",
    "SGB": "X",
    "SHC": "X",
    "SHP": "X",
    "SHR": "X",
    "SIB": "X",
    "SLR": "X",
    "SLZ": "X",
    "SMC": "X",
    "SME": "X",
    "SMF": "X",
    "SNC": "X",
    "SNN": "X",
    "SOC": "X",
    "SOY": "X",
    "SRZ": "X",
    "STY": "X",
    "SUB": "X",
    "SUN": "X",
    "SVA": "X",
    "SVV": "X",
    "SVW": "X",
    "SVX": "X",
    "SVY": "X",
    "SVZ": "X",
    "SYS": "X",
    "T11": "X",
    "T66": "X",
    "TA4": "X",
    "TAV": "X",
    "TBG": "X",
    "TBM": "X",
    "TCQ": "X",
    "TCR": "X",
    "TDD": "X",
    "TFQ": "X",
    "TH6": "X",
    "THC": "X",
    "THO": "X",
    "THR": "T",
    "THZ": "X",
    "TIH": "X",
    "TMB": "X",
    "TMD": "X",
    "TNB": "X",
    "TNR": "X",
    "TOQ": "X",
    "TPH": "X",
    "TPL": "X",
    "TPO": "X",
    "TPQ": "X",
    "TQI": "X",
    "TQQ": "X",
    "TRF": "X",
    "TRG": "X",
    "TRN": "X",
    "TRO": "X",
    "TRP": "W",
    "TRQ": "X",
    "TRW": "X",
    "TRX": "X",
    "TRY": "X",
    "TST": "X",
    "TTQ": "X",
    "TTS": "X",
    "TXY": "X",
    "TY1": "X",
    "TY2": "X",
    "TY3": "X",
    "TY5": "X",
    "TYB": "X",
    "TYI": "X",
    "TYJ": "X",
    "TYN": "X",
    "TYO": "X",
    "TYQ": "X",
    "TYR": "Y",
    "TYS": "X",
    "TYT": "X",
    "TYW": "X",
    "TYX": "X",
    "TYY": "X",
    "TZB": "X",
    "TZO": "X",
    "UMA": "X",
    "UN1": "X",
    "UN2": "X",
    "UNK": "X",
    "VAD": "X",
    "VAF": "X",
    "VAL": "V",
    "VB1": "X",
    "VDL": "X",
    "VLL": "X",
    "VLM": "X",
    "VMS": "X",
    "VOL": "X",
    "WLU": "X",
    "WPA": "X",
    "WRP": "X",
    "WVL": "X",
    "X2W": "X",
    "XCN": "X",
    "XCP": "X",
    "XDT": "X",
    "XPL": "X",
    "XPR": "X",
    "XSN": "X",
    "XX1": "X",
    "YCM": "X",
    "YOF": "X",
    "YTH": "X",
    "Z01": "X",
    "ZAL": "X",
    "ZCL": "X",
    "ZFB": "X",
    "ZU0": "X",
    "ZZJ": "X",
}

_PROTEIN_RESIDUES = frozenset(_AMINO_ACID_CODES.keys())


def residues_and_codes(variant_dicts, create_codes=True, code_dict=None):
    """
    Create set of nucleic residues and dict of 1-letter codes.

    Parameters
    ----------
    variant_dicts : list of dict
        Variant dictionaries (mapping canonical residue code to list of
        variants) to use
    create_codes : (list of) bool
        Which variants dicts (based on order) to use for creating one-letter
        codes; if not a list, the single value is used for all (default
        True)
    code_dict : dict
        Mapping of alias to 1-letter code to override algorithmic
        generation.
    """
    # create_codes should be a list of bool
    try:
        _ = iter(create_codes)
    except TypeError:
        create_codes = [create_codes] * len(variant_dicts)

    # inner sum over the values in one dict, outer sum over dicts
    residues = frozenset(sum([sum(list(dct.values()), []) for dct in variant_dicts], []))

    #  one_letter_dict
    all_std_names = sum([list(dct.keys()) for dct in variant_dicts], [])
    one_letter_dict = {name: name[-1] for name in all_std_names}

    # pick the variant dicts where we want the codes; get codes
    do_one_letter = [dct for (dct, one_letter) in zip(variant_dicts, create_codes) if one_letter]
    codes = {
        alias: one_letter_dict[parent] for dct in do_one_letter for parent, aliases in dct.items() for alias in aliases
    }

    if code_dict is not None:
        codes.update(code_dict)

    return residues, codes


_NUCLEIC_VARIANTS = {key: [key] for key in ["DG", "DA", "DT", "DC", "DI", "G", "A", "U", "C", "I"]}

_AMBER_VARIANTS = {
    "DA": ["DAN", "DA5", "DA3"],
    "DT": ["DTN", "DT5", "DT3"],
    "DC": ["DCN", "DC5", "DC3"],
    "DG": ["DGN", "DG5", "DG3"],
    "A": ["AN", "A5", "A3", "RAN", "RA5", "RA3"],
    "U": ["UN", "U5", "U3", "RUN", "RU5", "RU3"],
    "C": ["CN", "C5", "C3", "RCN", "RC5", "RC3"],
    "G": ["GN", "G5", "G3", "RGN", "RG5", "RG3"],
}

# protonated forms originally listed in ParmEd
_PROTONATED_VARIANTS = {"DA": ["DAP"], "DC": ["DCP"]}

_NUCLEIC_RESIDUES, _NUCLEIC_ACID_CODES = residues_and_codes(
    variant_dicts=[_NUCLEIC_VARIANTS, _AMBER_VARIANTS, _PROTONATED_VARIANTS],
    create_codes=True,
)
